### ISSUE TITLE
[Hardware Quirk] BufInfo_Add stride behaves strangely on hardware

### ISSUE THREAD

**Issue by fordcars** [devkitPro/citro3d#57]
It looks like when the stride given to `BufInfo_Add` is larger than the attribute, behavior is very unstable. It will often crash depending on what stride you use, or simply display incorrect data. It will run fine on Citra.

Examples:
```c++
AttrInfo_Init(attrInfo);
AttrInfo_AddLoader(attrInfo, 0, GPU_FLOAT, 2);

// No crash
BufInfo_Add(mBufferInfo, data, sizeof(float) * 2, 1, 0x0);

// Crash
BufInfo_Add(mBufferInfo, data, sizeof(float) * 4, 1, 0x0);
```

**Comment by fincs** [comment]
This 3dbrew wiki article might come in handy: https://www.3dbrew.org/wiki/GPU/Pitfalls
